# Flash from the Pi without arduino-cli (Debian avr-gcc + Arduino.mk).
#   cd firmware/arduino_robot && make upload
BOARD_TAG = uno
MONITOR_PORT = /dev/ttyACM0
ARDUINO_DIR = /usr/share/arduino
AVRDUDE = /usr/bin/avrdude
AVRDUDE_CONF = /etc/avrdude.conf
include /usr/share/arduino/Arduino.mk
